### ISSUE TITLE
Enum fields are treated as objects but should be treated as scalars

### ISSUE THREAD

**Issue by jorrit** [mghoneimy/php-graphql-oqm#11]
In `SchemaClassGenerator::generateObject()` and `SchemaClassGenerator::appendQueryObjectFields()` it seems that enum fields are treated as object fields. This generates query bodies like these:

```php
    public function selectEnumField(ParentEnumFieldArgumentsObject $argsObject = null)
    {
        $object = new EnumFieldQueryObject("enumField");
        if ($argsObject !== null) {
            $object->appendArguments($argsObject->toArray());
        }
        $this->selectField($object);
    
        return $object;
    }
```

However, `EnumFieldQueryObject` is never generated because it is only generated for object types. I think somewhere in `SchemaClassGenerator::appendQueryObjectFields()` a code path should be taken that looks more like scalar.

Am I missing something perhaps?

**Comment by mghoneimy** [comment]
So two things about this:
1. Yes, this is a bug. Selection methods for ENUM fields should be like scalar selection methods, not object selection methods. The fix for this should be easy though.
2. Despite this being a bug in generating the selection method, `EnumFieldQueryObject` class should get generated normally if it exists in the API schema, which should always be the case.

I tried this on an example locally and it worked as expected, Enum class got generated, the selection method got generated incorrectly.

From the looks of it, modifying `SchemaClassGenerator.php` line `100` should fix the issue, I haven't applied the fix nor run any tests though.

Would you like to work on this or should I allocate time for it in my schedule? @jorrit

**Comment by jorrit** [comment]
I have created a PR. I've found some other issues also, so more PR's are upcoming.
